kind: wasmer.io/App.v0
name: fastapi-crud
package: yourname/fastapi-crud@0.1.0
debug: true

capabilities:
  database:
    engine: mysql

locality:
  regions:
    - us-socal1

env:
  DB_HOST: ""
  DB_PORT: ""
  DB_NAME: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""

cli_args:
  - "python"
  - "-m"
  - "uvicorn"
  - "main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8080"
  - "--log-level"
  - "info"
